### ISSUE TITLE
Invalid binary compiled for swiftlint

### ISSUE THREAD

**Issue by sk-** [Cyberbeni/install-swift-tool#68]
The actions looks great, however the compiled binary for swiftlint fails with the error:

```
Run swiftlint --strict
  swiftlint --strict
  shell: /bin/bash -e {0}
Loading configuration from '.swiftlint.yml'
Fatal error: Loading libsourcekitdInProc.so failed: file SourceKittenFramework/library_wrapper.swift, line 39
/home/runner/work/_temp/8c14c813-f4f1-4307-b0e6-78983f636737.sh: line 1:  3112 Illegal instruction     (core dumped) swiftlint --strict
Error: Process completed with exit code 132.
```

Below is my configuration

```yaml
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install swiftlint
      uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/realm/SwiftLint
        version: "0.39.2"  # TODO: change to 0.40.3

    - name: Lint
      run: swiftlint --strict
```

Is there something I'm missing?

The only difference I could find with respect to the build command we have in CircleCI is that we are passing the flag `--static-swift-stdlib`.

Also, I noted that the tests don't execute the compiled files, they just check whether they are in the path.
ps: It'd be great if you could add https://github.com/apple/swift-format to the tests

**Comment by sk-** [comment]
I managed to make it work by running instead `LINUX_SOURCEKIT_LIB_PATH=/usr/share/swift/usr/lib swiftlint --strict`

**Comment by Cyberbeni** [comment]
Oh, I was not getting notifications from this repo.
Never had similar issue with SwiftFromat in [my workflow](https://github.com/Cyberbeni/TypedNotificationCenter/blob/master/.github/workflows/lint.yml), so I assumed that if it builds, it runs. I'll take a look at this issue on the weekend.

**Comment by Cyberbeni** [comment]
After a quick [search](https://www.google.com/search?q=LINUX_SOURCEKIT_LIB_PATH) it seems like this env var is the official solution for this and the we'll just have to find `libsourcekitdInProc.so` and export it's path on Linux.

**Comment by Cyberbeni** [comment]
Fixed in v2.1.8

**Comment by Cyberbeni** [comment]
> ps: It'd be great if you could add https://github.com/apple/swift-format to the tests

That would also require some additional [version matching](https://github.com/apple/swift-format#matching-swift-format-to-your-swift-version) (or specifying a fix swift version and using docker/swiftenv to download it at the start of the workflow). If you already have a working workflow for that, feel free to make a PR.

**Comment by Cyberbeni** [comment]
SInce I already knew how to do it, I added test for apple/swift-format to run after merge and on manual trigger with Swift 5.3
